### PR TITLE
catch Exception when loading image points

### PR DESCRIPTION
**Pull request by yl-1993**
Avoid mishape error when calling aligner

### CODE REVIEW

**Comment by alyssaq** [comment]
Could you paste the exception? I think the error is coming from locator.py and the exception should either be placed there or the stasm binary can be modified.

**Comment by yl-1993** [comment]
Thanks for quick reply. When I try to average a folder containing 2000+ images with same size, the following error would easily be thrown. It seems that the error is coming from aligner.py. 
"Traceback (most recent call last):
  File "facemorpher/averager.py", line 98, in <module>
    args['--out'], args['--plot'])
  File "facemorpher/averager.py", line 67, in averager
    img, points = load_image_points(path, size)
  File "facemorpher/averager.py", line 54, in load_image_points
    return aligner.resize_align(img, points, size)
  File "/home/yanglei/data/face_morpher-master/facemorpher/aligner.py", line 97, in resize_align
    img[roi_y:roi_y+roi_h, roi_x:roi_x+roi_w])
ValueError: could not broadcast input array from shape (434,358,3) into shape (433,358,3)
"

**Comment by alyssaq** [comment]
Looks like an error at resize_align. I guess the function is not handling large images too well.
What's the image resolution? Could you email me one image?

**Comment by alyssaq** [comment]
Thanks for sending me some sample images! 
It helped me in finding the bug which was due to my porting of face morpher to python3. The division by ints in python3 are returned as floats (unlike python2 which simply casts to int implictly) so I had to cast the coordinates. Ive merged the [fix into master](https://github.com/alyssaq/face_morpher/commit/beeec399cd8bf7dfd0bb8c8e078f6dd878975dcb).

Ive tested it with your images and it works now 😄 
Feel free to test it with the fix and let me know how it goes!

**Comment by yl-1993** [comment]
Hi alyssaq, I've tested the new code with 2,500 images and it worked pretty well. 
Thanks for your work!!

**Comment by alyssaq** [comment]
Yay! 😄

**Pull request closed without merging**
